# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:
  en: Slimcoin. A cryptocurrency for the long term.
  es: Slimcoin. La criptomoneda duradera y estable.
  pl: Slimcoin. Długoterminowa kryptowaluta.
  ru: Слимкоин. Криптовалюта для долгосрочной перспективы.
# email: your-email@domain.com
description:
  en: Slimcoin is a energy-efficient cryptocurrency designed for decentralization and stability. It's the first cryptocurrency using Proof of Burn or virtual mining.
  es: Slimcoin es una criptomoneda eficiente, decentralizada y estable. Es la primera criptomoneda que usa Proof of Burn o minería virtual. 
  pl: Slimcoin jest energooszczędną kryptowalutą zaprojektowaną w celu decentralizacji i stabilności. Jest to pierwsza kryptowaluta używająca konsensus Proof of Burn/ wirtualnego kopania.
  ru: Слимкоин. Криптовалюта для долгосрочной перспективы.
index:
  en:
  es: inicio.html
  pl: index-pl.html
  ru: index-ru.html
# feed:
#  en: /feed.xml
#  es: /feed_es.xml
# baseurl: "/pages" # the subpath of your site, e.g. /blog
footertitle:
  en: Use & Participate
  es: Usar & Participar
  pl: Użycie i przystąpienie
  ru: Использование и участие
resourcesheading:
  en: Resources
  es: Recursos
  pl: Źródła
  ru: Ресурсы
socialheading:
  en: Social media
  es: Medios sociales
  pl: Media społecznościowe
  ru: Социальные медиа
toolsheading:
  en: Tools
  es: Herramientas
  pl: Narzędzia
  ru: Инструменты
languagestring:
  en: English
  es: Español
  pl: Polski
  ru: Русский

url: "http://slimco.in" # the base hostname & protocol for your site
twitter_username: slimcoin_club
github_username: slimcoin-project

# Build settings
markdown: kramdown
